import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "@/globals.css";
import NavBar from "@/components/ui/NavBar";
import Header from "@/components/ui/Header";
import SessionProvider from "@/provider/session";
const notoSans = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bizbee Middleware",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${notoSans.variable} antialiased md:flex min-h-screen`}>
        <SessionProvider>
          <NavBar />
          <div className="flex flex-1 md:pe-4 md:py-4 max-md:min-h-[calc(100svh-96px)] max-md:px-4 flex-col">
            <Header />
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
